[project]
name = "mlops-it-support-ticket-priority-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MarT1AZ", email = "mewpudit@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "mlflow>=3.16.0",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "pytest>=9.1.1",
    "s3fs>=2026.7.0",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
]

[project.scripts]
mlops-it-support-ticket-priority-model = "mlops_it_support_ticket_priority_model:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
